using NUnit.Framework;
using OllamaSharp;
using OllamaSharp.Models.Chat;
using Shouldly;

namespace Tests;

#pragma warning disable CS8602 // Dereference of a possibly null reference.
#pragma warning disable CS8604 // Possible null reference argument.

/// <summary>
/// Contains integration tests for the <see cref="Chat"/> class.
/// </summary>
public class ChatTests
{
	/// <summary>
	/// Tests for the <see cref="Chat.SendAsync(string, CancellationToken)"/> method.
	/// </summary>
	public class SendMethod : ChatTests
	{
		/// <summary>
		/// Verifies that an assistant's answer is streamed correctly and appended to the chat history.
		/// </summary>
		[Test]
		public async Task Sends_Assistant_Answer_To_Streamer()
		{
			var ollama = new TestOllamaApiClient();
			ollama.SetExpectedChatResponses(
				new ChatResponseStream { Message = CreateMessage(ChatRole.Assistant, "Hi hu") },
				new ChatResponseStream { Message = CreateMessage(ChatRole.Assistant, "man, how") },
				new ChatResponseStream { Message = CreateMessage(ChatRole.Assistant, " are you?") });

			var chat = new Chat(ollama);
			var answer = await chat.SendAsync("henlo", CancellationToken.None).StreamToEndAsync();

			answer.ShouldBe("Hi human, how are you?");

			chat.Messages.Last().Role.ShouldBe(ChatRole.Assistant);
			chat.Messages.Last().Content.ShouldBe("Hi human, how are you?");
		}

		/// <summary>
		/// Verifies that a tool call generated by the assistant is streamed and recorded correctly.
		/// </summary>
		[Test]
		public async Task Sends_Assistant_ToolsCall_To_Streamer()
		{
			var ollama = new TestOllamaApiClient();
			ollama.SetExpectedChatResponses(
				new ChatResponseStream
				{
					Message = new Message
					{
						Role = ChatRole.Assistant,
						Content = "",
						ToolCalls = [
							new Message.ToolCall
							{
								Function = new Message.Function
								{
									Name = "get_current_weather",
									Arguments = new Dictionary<string, object?>()
									{
										["format"] = "celsius",
										["location"] = "Los Angeles2, CA",
										["number"] = 30,
									}
								}
							}
						]
					}
				});

			var chat = new Chat(ollama) { ToolInvoker = null! }; // we have no tool implementation in this test
			chat.AllowRecursiveToolCalls = false; // this is required because the expected chat response contains a tool call that would cause an infinite loop
			await chat.SendAsync("How is the weather in LA?", CancellationToken.None).StreamToEndAsync();

			chat.Messages.Last().Role.ShouldBe(ChatRole.Assistant);
			chat.Messages.Last().ToolCalls.Count().ShouldBe(1);
			chat.Messages.Last().ToolCalls.ElementAt(0).Function.Name.ShouldBe("get_current_weather");
		}

		/// <summary>
		/// Verifies that a system prompt supplied to the constructor is sent as the first message.
		/// </summary>
		[Test]
		public async Task Sends_System_Prompt_Message()
		{
			var ollama = new TestOllamaApiClient();
			var chat = new Chat(ollama, "Speak like a pirate.");
			await chat.SendAsync("henlo", CancellationToken.None).StreamToEndAsync();

			chat.Messages.First().Role.ShouldBe(ChatRole.System);
			chat.Messages.First().Content.ShouldBe("Speak like a pirate.");
		}

		/// <summary>
		/// Verifies that user messages are added to the chat history with the correct role and content.
		/// </summary>
		[Test]
		public async Task Sends_Messages_As_User()
		{
			var ollama = new TestOllamaApiClient();
			var chat = new Chat(ollama);

			await chat.SendAsync("henlo", CancellationToken.None).StreamToEndAsync();

			chat.Messages.First().Role.ShouldBe(ChatRole.User);
			chat.Messages.First().Content.ShouldBe("henlo");
		}

		/// <summary>
		/// Verifies that image byte arrays are encoded as Base64 strings and attached to the user message.
		/// </summary>
		[Test]
		public async Task Sends_Image_Bytes_As_Base64()
		{
			var bytes1 = System.Text.Encoding.ASCII.GetBytes("ABC");
			var bytes2 = System.Text.Encoding.ASCII.GetBytes("ABD");

			var ollama = new TestOllamaApiClient();

			var chat = new Chat(ollama);
			await chat.SendAsync("", [bytes1, bytes2], CancellationToken.None).StreamToEndAsync();

			chat.Messages.Single(m => m.Role == ChatRole.User).Images.ShouldBe(["QUJD", "QUJE"], ignoreOrder: true);
		}
	}

	/// <summary>
	/// Tests for the <see cref="Chat.SendAsAsync(ChatRole, string, CancellationToken)"/> method.
	/// </summary>
	public class SendAsMethod : ChatTests
	{
		/// <summary>
		/// Verifies that a message can be sent with an explicitly defined role and that the assistant's response follows.
		/// </summary>
		[Test]
		public async Task Sends_Messages_As_Defined_Role()
		{
			var ollama = new TestOllamaApiClient();
			ollama.SetExpectedChatResponses(
				new ChatResponseStream { Message = CreateMessage(ChatRole.Assistant, "Hi") },
				new ChatResponseStream { Message = CreateMessage(ChatRole.Assistant, " tool.") });

			var chat = new Chat(ollama);
			await chat.SendAsAsync(ChatRole.Tool, "Henlo assistant.", CancellationToken.None).StreamToEndAsync();

			var history = chat.Messages.ToArray();
			history.Length.ShouldBe(2);
			history[0].Role.ShouldBe(ChatRole.Tool);
			history[0].Content.ShouldBe("Henlo assistant.");
			history[1].Role.ShouldBe(ChatRole.Assistant);
			history[1].Content.ShouldBe("Hi tool.");
		}

		/// <summary>
		/// Verifies that image byte arrays are encoded as Base64 strings when using <see cref="Chat.SendAsAsync"/>.
		/// </summary>
		[Test]
		public async Task Sends_Image_Bytes_As_Base64()
		{
			var ollama = new TestOllamaApiClient();

			var bytes1 = System.Text.Encoding.ASCII.GetBytes("ABC");
			var bytes2 = System.Text.Encoding.ASCII.GetBytes("ABD");

			var chat = new Chat(ollama);
			await chat.SendAsAsync(ChatRole.User, "", [bytes1, bytes2], CancellationToken.None).StreamToEndAsync();

			chat.Messages.Single(m => m.Role == ChatRole.User).Images.ShouldBe(["QUJD", "QUJE"], ignoreOrder: true);
		}
	}

	/// <summary>
	/// Tests for the <see cref="Chat.Messages"/> property setter and getter.
	/// </summary>
	public class MessagesPropertyMethod : ChatTests
	{
		/// <summary>
		/// Verifies that assigning a new collection replaces the existing chat history.
		/// </summary>
		[Test]
		public void Replaces_Chat_History()
		{
			var ollama = new TestOllamaApiClient();

			var chat = new Chat(ollama)
			{
				Messages = [new Message { Content = "A", Role = ChatRole.System }]
			};
			chat.Messages.Single().Content.ShouldBe("A");

			chat.Messages = [new Message { Content = "B", Role = ChatRole.System }];
			chat.Messages.Single().Content.ShouldBe("B");
		}
	}

	protected static Message CreateMessage(ChatRole role, string content)
		=> new() { Role = role, Content = content };
}

#pragma warning restore CS8602 // Dereference of a possibly null reference.
#pragma warning restore CS8604 // Possible null reference argument.
